name: 'Get package info'
description: 'Action for getting information from package.json file'
branding:
  icon: 'box'
  color: 'red'

inputs:
  path:
    description: 'Path to package.json file'
    required: false
    default: ./

outputs:
  name:
    description: 'Package name'

  version:
    description: 'Package version'

  is-release-candidate:
    description: 'Is the package version a release candidate'  

  npmjs-link:
    description: 'Link to npmjs.com package page'

runs:
  using: 'node16'
  main: 'dist/index.js'
